### ISSUE TITLE
wilcard not working

### ISSUE THREAD

**Issue by hhsievertsen** [rOpenGov/dkstat#23]
Hi,
thanks for creating this. 
It works well for me when using this example: 

`births <- dst_get_data(table = "BEV3A", BEVÆGELSEV = "Levendefødte" ,Tid="1901M01",lang = "da")`

but when I replace "19091M01" with the wildcard: 

`births <- dst_get_data(table = "BEV3A", BEVÆGELSEV = "Levendefødte" ,Tid="*",lang = "da")`

I get the error message

> Error: $ operator is invalid for atomic vectors

Any suggestions?
Cheers,
Hans

**Comment by krose** [comment]
Hi Hans

I would recommend that you switch to the package that @mikkelkrogsholm made. Here is the [link](https://github.com/mikkelkrogsholm/statsDK) for his package. I don't like the interface I ended up with and I think Mikkels solution is better.

Maybe we should consider linking to his package inhere instead of dkstat.

/Kenneth

**Comment by hhsievertsen** [comment]
Hi Kenneth,
great thanks for the quick response and the link! 
Except for the wildcard issue your package worked fine for me!
Best,
Hans

**Comment by emilBeBri** [comment]
I'd like to second that - I think the package works great, and I'd rather use that than a more tidyverse centered approach from the package by Mikkel K, not a big fan of the tibble-tidyverse version of R. So this is much better!
